namespace MultiFunPlayer.Input;

internal interface IInputGestureDescriptor;
internal interface IButtonInputGestureDescriptor : IInputGestureDescriptor;
internal interface IAxisInputGestureDescriptor : IInputGestureDescriptor;